# Generated by Django 3.2 on 2023-01-26 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ('pub_date',), 'verbose_name': 'отзыв', 'verbose_name_plural': 'отзывы'},
        ),
    ]
